name: Daily Match Fetch

on:
  schedule:
    # - cron: "0 0 * * *"  
  workflow_dispatch:     # 手动触发

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch script
        run: python fetch_and_mail.py
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
